# Generated by Django 3.2.9 on 2021-12-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best', '0005_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
